entity: shreyaspadhy
project: cais
program: main.py

method: grid
parameters:
  model:
    values: ['log_sonar', 'log_ionosphere', 'lorenz', 'brownian', 'banana', 'seeds']
  boundmode:
    values: ['MCD_ULA', 'MCD_ULA_sn', 'UHA', 'MCD_U_a-lp-sn', 'MCD_CAIS_sn', 'MCD_CAIS_UHA_sn']
  lr:
    values: [1e-3, 1e-4, 1e-5]

command:
  - python
  - ${program}
  - --config
  - configs/base.py