entity: shreyaspadhy
project: cais
program: main.py

method: grid
parameters:
  nbridges:
    values: [256, 128, 64, 32, 16, 8]
  model:
    values: ['gmm']
  boundmode:
    values: ['MCD_CAIS_sn']
  lr:
    values: [1e-3, 1e-4]
  N:
    values: [1]
  iters:
    values: [11000]
  init_eps:
    values: [0.01, 0.02, 0.05, 0.1]
  init_sigma:
    values: [1, 2, 3]
  pretrain_mfvi:
    values: [False]
  train_vi:
    values: [False, True]
  train_eps:
    values: [False]

command:
  - python
  - ${program}
  - --config
  - configs/base.py