entity: shreyaspadhy
project: cais
program: main.py

method: grid
parameters:
  boundmode:
    values: ['MCD_CAIS_sn', 'MCD_CAIS_UHA_sn']
  model:
    # values: ['log_sonar', 'log_ionosphere', 'lorenz', 'brownian', 'banana', 'seeds']
    values: ['funnel']
  nbridges:
    values: [256, 128, 64, 32, 16, 8]
  N:
    values: [300]
  iters:
    values: [11000]
  pretrain_mfvi:
    values: [False]
  train_eps:
    values: [False]
  init_eps:
    values: [1e-4, 1e-3, 1e-2, 1e-1, 3e-1, 5e-1, 1]
  lr:
    values: [5e-2, 1e-2, 5e-3, 1e-3]
  emb_dim:
    values: [48]
  

command:
  - python
  - ${program}
  - --config
  - configs/base.py