entity: shreyaspadhy
project: cais
program: nice_run.py

method: grid
parameters:
  alpha:
    values: [1e-6, 0.05]
  n_bits:
    values: [3, 5, 8]
  im_size:
    values: [7, 14, 28]

command:
  - python
  - ${program}